version: '3.8'

networks:
  intranet:
    driver: bridge

volumes:
  data:
    driver: local

services:
  #######################################
  ############## POSTGRES ###############
  #######################################
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: market_postgres
    volumes:
      - ${DATA_PATH_HOST}/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - intranet
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  market_ledger:
    build:
      context: ./
    container_name: market_ledger_api
    networks:
      - intranet
    volumes:
      - ./:/app
    ports:
      - "50000:50000"
      - "40000:40000"
    entrypoint: sh -c '/usr/local/bin/wait-for postgres:5432 -- go mod vendor && go run -mod=vendor /app/cmd/ledger/ledger.go serve --config "/app/configs/ledger.yml" --purge-db'
