// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.3
// source: market-ledger-service.proto

package v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Invoice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique ID of the Issuer
	IssuerId uint64 `protobuf:"varint,1,opt,name=issuerId,proto3" json:"issuerId,omitempty"`
	// Unique invoice name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Full price of the Invoice
	FaceValue float64 `protobuf:"fixed64,3,opt,name=faceValue,proto3" json:"faceValue,omitempty"`
	// Price that needs to be covered, usually smaller but not greater than the rawValue
	NeededValue float64 `protobuf:"fixed64,4,opt,name=neededValue,proto3" json:"neededValue,omitempty"`
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_ledger_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_market_ledger_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_market_ledger_service_proto_rawDescGZIP(), []int{0}
}

func (x *Invoice) GetIssuerId() uint64 {
	if x != nil {
		return x.IssuerId
	}
	return 0
}

func (x *Invoice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Invoice) GetFaceValue() float64 {
	if x != nil {
		return x.FaceValue
	}
	return 0
}

func (x *Invoice) GetNeededValue() float64 {
	if x != nil {
		return x.NeededValue
	}
	return 0
}

type SellResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID of the created Invoice
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SellResponse) Reset() {
	*x = SellResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_ledger_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellResponse) ProtoMessage() {}

func (x *SellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_ledger_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellResponse.ProtoReflect.Descriptor instead.
func (*SellResponse) Descriptor() ([]byte, []int) {
	return file_market_ledger_service_proto_rawDescGZIP(), []int{1}
}

func (x *SellResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_market_ledger_service_proto protoreflect.FileDescriptor

var file_market_ledger_service_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2d, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76,
	0x31, 0x22, 0x79, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x66, 0x61, 0x63, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x09, 0x66, 0x61, 0x63, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x65,
	0x65, 0x64, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0b, 0x6e, 0x65, 0x65, 0x64, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1e, 0x0a, 0x0c,
	0x53, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x32, 0x35, 0x0a, 0x0c,
	0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x04,
	0x53, 0x65, 0x6c, 0x6c, 0x12, 0x0b, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63,
	0x65, 0x1a, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_market_ledger_service_proto_rawDescOnce sync.Once
	file_market_ledger_service_proto_rawDescData = file_market_ledger_service_proto_rawDesc
)

func file_market_ledger_service_proto_rawDescGZIP() []byte {
	file_market_ledger_service_proto_rawDescOnce.Do(func() {
		file_market_ledger_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_market_ledger_service_proto_rawDescData)
	})
	return file_market_ledger_service_proto_rawDescData
}

var file_market_ledger_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_market_ledger_service_proto_goTypes = []interface{}{
	(*Invoice)(nil),      // 0: v1.Invoice
	(*SellResponse)(nil), // 1: v1.SellResponse
}
var file_market_ledger_service_proto_depIdxs = []int32{
	0, // 0: v1.MarketLedger.Sell:input_type -> v1.Invoice
	1, // 1: v1.MarketLedger.Sell:output_type -> v1.SellResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_market_ledger_service_proto_init() }
func file_market_ledger_service_proto_init() {
	if File_market_ledger_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_market_ledger_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Invoice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_ledger_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SellResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_market_ledger_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_ledger_service_proto_goTypes,
		DependencyIndexes: file_market_ledger_service_proto_depIdxs,
		MessageInfos:      file_market_ledger_service_proto_msgTypes,
	}.Build()
	File_market_ledger_service_proto = out.File
	file_market_ledger_service_proto_rawDesc = nil
	file_market_ledger_service_proto_goTypes = nil
	file_market_ledger_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MarketLedgerClient is the client API for MarketLedger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MarketLedgerClient interface {
	Sell(ctx context.Context, in *Invoice, opts ...grpc.CallOption) (*SellResponse, error)
}

type marketLedgerClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketLedgerClient(cc grpc.ClientConnInterface) MarketLedgerClient {
	return &marketLedgerClient{cc}
}

func (c *marketLedgerClient) Sell(ctx context.Context, in *Invoice, opts ...grpc.CallOption) (*SellResponse, error) {
	out := new(SellResponse)
	err := c.cc.Invoke(ctx, "/v1.MarketLedger/Sell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketLedgerServer is the server API for MarketLedger service.
type MarketLedgerServer interface {
	Sell(context.Context, *Invoice) (*SellResponse, error)
}

// UnimplementedMarketLedgerServer can be embedded to have forward compatible implementations.
type UnimplementedMarketLedgerServer struct {
}

func (*UnimplementedMarketLedgerServer) Sell(context.Context, *Invoice) (*SellResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sell not implemented")
}

func RegisterMarketLedgerServer(s *grpc.Server, srv MarketLedgerServer) {
	s.RegisterService(&_MarketLedger_serviceDesc, srv)
}

func _MarketLedger_Sell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Invoice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketLedgerServer).Sell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.MarketLedger/Sell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketLedgerServer).Sell(ctx, req.(*Invoice))
	}
	return interceptor(ctx, in, info, handler)
}

var _MarketLedger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.MarketLedger",
	HandlerType: (*MarketLedgerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sell",
			Handler:    _MarketLedger_Sell_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market-ledger-service.proto",
}
